#!/bin/bash
#SBATCH --job-name="PPFlow training"
#SBATCH --partition=gpu
#SBATCH --time=3-01:00:00
#SBATCH --gres=gpu:1           # Request 1 GPU
#SBATCH --cpus-per-task=8     # Request 8 CPUs
#SBATCH --mem=64G


cd /gpfs/helios/home/tootsi/homing/ppflow
conda init bash
conda activate ppflow
srun python train_ppf.py --resume '/gpfs/helios/home/tootsi/homing/ppflow/logs/ppflow_2024_08_12__19_43_32/checkpoints/151000.pt'

